<?php

namespace Container36ZOhSh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7bDjG1dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7bDjG1d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7bDjG1d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'subelementfields' => ['privates', '.errored..service_locator.7bDjG1d.App\\Entity\\SubelementFields', NULL, 'Cannot autowire service ".service_locator.7bDjG1d": it references class "App\\Entity\\SubelementFields" but no such service exists.'],
        ], [
            'subelementfields' => 'App\\Entity\\SubelementFields',
        ]);
    }
}
