<?php

namespace ContainerZdoCHer;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G4iNSV6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G4iNSV6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G4iNSV6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'elements' => ['privates', 'App\\Repository\\ElementRepository', 'getElementRepositoryService', true],
            'tags' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'elements' => 'App\\Repository\\ElementRepository',
            'tags' => 'App\\Repository\\TagRepository',
        ]);
    }
}
