<?php

namespace ContainerDHffW8q;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubelementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.25IZi3d.App\Entity\Subelement' shared service.
     *
     * @return \App\Entity\Subelement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.25IZi3d": it references class "App\\Entity\\Subelement" but no such service exists.');
    }
}
