<?php

namespace ContainerQRXmkmn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5M9div4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5M9div4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5M9div4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dateFields' => ['privates', 'App\\Repository\\DateFieldsRepository', 'getDateFieldsRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'dateFields' => 'App\\Repository\\DateFieldsRepository',
            'serializer' => '?',
        ]);
    }
}
