<?php

namespace ContainerJcPiVmn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N088AafService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N088Aaf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N088Aaf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filefields' => ['privates', '.errored..service_locator.N088Aaf.App\\Entity\\FileFields', NULL, 'Cannot autowire service ".service_locator.N088Aaf": it references class "App\\Entity\\FileFields" but no such service exists.'],
        ], [
            'filefields' => 'App\\Entity\\FileFields',
        ]);
    }
}
