<?php

namespace ContainerJcPiVmn;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileFields2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.div2LH8.App\Entity\FileFields' shared service.
     *
     * @return \App\Entity\FileFields
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.div2LH8": it references class "App\\Entity\\FileFields" but no such service exists.');
    }
}
