<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DateFields extends \App\Entity\DateFields implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'element', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'subelement', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'title', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'content', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'position', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'parentFields', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'childFields'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'element', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'subelement', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'title', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'content', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'position', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'parentFields', '' . "\0" . 'App\\Entity\\DateFields' . "\0" . 'childFields'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DateFields $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getElement(): ?\App\Entity\Element
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElement', []);

        return parent::getElement();
    }

    /**
     * {@inheritDoc}
     */
    public function setElement(\App\Entity\Element $element): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setElement', [$element]);

        return parent::setElement($element);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubelement(): ?\App\Entity\Subelement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubelement', []);

        return parent::getSubelement();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubelement(?\App\Entity\Subelement $subelement): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubelement', [$subelement]);

        return parent::setSubelement($subelement);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent(\DateTime $content): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition(int $position): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentFields(): ?\App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentFields', []);

        return parent::getParentFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentFields(?\App\Entity\DateFields $parentFields): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentFields', [$parentFields]);

        return parent::setParentFields($parentFields);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildFields(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildFields', []);

        return parent::getChildFields();
    }

    /**
     * {@inheritDoc}
     */
    public function addChildField(\App\Entity\DateFields $childField): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChildField', [$childField]);

        return parent::addChildField($childField);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChildField(\App\Entity\DateFields $childField): \App\Entity\DateFields
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChildField', [$childField]);

        return parent::removeChildField($childField);
    }

}
