<?php

namespace ContainerXNwjIjK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateFieldsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cZ2Ga9K.App\Entity\DateFields' shared service.
     *
     * @return \App\Entity\DateFields
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cZ2Ga9K": it references class "App\\Entity\\DateFields" but no such service exists.');
    }
}
