<?php

namespace ContainerQgPPviy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DbY8AGkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dbY8AGk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dbY8AGk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'element' => ['privates', '.errored..service_locator.dbY8AGk.App\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.dbY8AGk": it references class "App\\Entity\\Element" but no such service exists.'],
            'subelements' => ['privates', 'App\\Repository\\SubelementRepository', 'getSubelementRepositoryService', true],
            'tags' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'element' => 'App\\Entity\\Element',
            'subelements' => 'App\\Repository\\SubelementRepository',
            'tags' => 'App\\Repository\\TagRepository',
        ]);
    }
}
