<?php

namespace ContainerQgPPviy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubelementFieldsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7bDjG1d.App\Entity\SubelementFields' shared service.
     *
     * @return \App\Entity\SubelementFields
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7bDjG1d": it references class "App\\Entity\\SubelementFields" but no such service exists.');
    }
}
