<?php

namespace Container1ywpD9q;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BrTJSojService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.brTJSoj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.brTJSoj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'numberfields' => ['privates', '.errored..service_locator.brTJSoj.App\\Entity\\NumberFields', NULL, 'Cannot autowire service ".service_locator.brTJSoj": it references class "App\\Entity\\NumberFields" but no such service exists.'],
        ], [
            'numberfields' => 'App\\Entity\\NumberFields',
        ]);
    }
}
