<?php

namespace ContainerUfUw8wJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getElement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c5BQ3qw.App\Entity\Element' shared service.
     *
     * @return \App\Entity\Element
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.c5BQ3qw": it references class "App\\Entity\\Element" but no such service exists.');
    }
}
