<?php

namespace ContainerGzxxhGX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q4BYX5KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q4BYX5K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q4BYX5K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'textFields' => ['privates', '.errored..service_locator.Q4BYX5K.App\\Entity\\TextFields', NULL, 'Cannot autowire service ".service_locator.Q4BYX5K": it references class "App\\Entity\\TextFields" but no such service exists.'],
        ], [
            'em' => '?',
            'serializer' => '?',
            'textFields' => 'App\\Entity\\TextFields',
        ]);
    }
}
