<?php

namespace ContainerGzxxhGX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3ONUzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3_O_NUz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3_O_NUz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dateFields' => ['privates', '.errored..service_locator.3_O_NUz.App\\Entity\\DateFields', NULL, 'Cannot autowire service ".service_locator.3_O_NUz": it references class "App\\Entity\\DateFields" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'dateFields' => 'App\\Entity\\DateFields',
            'em' => '?',
            'serializer' => '?',
        ]);
    }
}
