<?php

namespace ContainerGzxxhGX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTextFieldsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Q4BYX5K.App\Entity\TextFields' shared service.
     *
     * @return \App\Entity\TextFields
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Q4BYX5K": it references class "App\\Entity\\TextFields" but no such service exists.');
    }
}
