<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdoCHer\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdoCHer/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZdoCHer.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZdoCHer\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZdoCHer\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZdoCHer',
    'container.build_id' => '86443892',
    'container.build_time' => 1671702418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZdoCHer');
