<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWx9F29\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWx9F29/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXWx9F29.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXWx9F29\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXWx9F29\App_KernelDevDebugContainer([
    'container.build_hash' => 'XWx9F29',
    'container.build_id' => '8eabe911',
    'container.build_time' => 1673457263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWx9F29');
