<?php

namespace ContainerHOPpixi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9CRX9VxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9CRX9Vx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9CRX9Vx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'element' => ['privates', '.errored..service_locator.9CRX9Vx.App\\Entity\\Element', NULL, 'Cannot autowire service ".service_locator.9CRX9Vx": it references class "App\\Entity\\Element" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'element' => 'App\\Entity\\Element',
        ]);
    }
}
